mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.infervision.dao
  type-handlers-package: com.infervision.config

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver

  redis:
  profiles:
    active: dev

logging:
  config: classpath:logback-spring.xml
  level: debug

